#!/usr/bin/env bash
#ddev-generated
## Generates the server configuration that serves the worktrees.
##
## Addresses: <worktree>.<project>.<tld> -> .ddev/branchery/var/docroots/<worktree>
##
## There is one link per worktree pointing at its web directory, so every
## project can have a docroot of its own and a new worktree is reachable right
## away, without reloading the web server.
##
## Supports nginx and Apache -- which one runs is up to the project.
##
## Two halves: the configuration is written to standard output, and applying it
## is what happens below. That is what lets the first half be read by a test --
## it needs no server, no project and no root, and this file is the most
## fragile thing this add-on ships. See tests/scripts.bats.
set -euo pipefail

DOCROOTS="/var/www/html/.ddev/branchery/var/docroots"

# The addresses hang under the project's own name.
tld="${DDEV_SITENAME:-ddev}.${DDEV_TLD:-ddev.site}"
escaped_tld="$(printf '%s' "$tld" | sed 's/\./\\./g')"

nginx_config() {
    cat <<EOF
# Generated by the worktree management -- do not edit by hand.
server {
    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    # The first part of the hostname names the worktree.
    server_name ~^(?<worktree>[a-z0-9-]+)\\.${escaped_tld}\$;
    root ${DOCROOTS}/\$worktree;

    include /etc/nginx/monitoring.conf;
    index index.php index.html;
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    location / {
        absolute_redirect off;
        try_files \$uri \$uri/ /index.php\$is_args\$args;
    }

    location ~ \\.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\\.php)(/.+)\$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME \$host;
        fastcgi_param HTTPS \$fcgi_https;
    }

    include /mnt/ddev_config/nginx/*.conf;
}
EOF
}

apache_config() {
    local block
    block() {
        local port="$1" ssl="$2"
        cat <<EOF
<VirtualHost *:${port}>
    ServerName worktrees.${tld}
    ServerAlias *.${tld}
${ssl}
    UseCanonicalName Off
    VirtualDocumentRoot ${DOCROOTS}/%1

    RewriteEngine On
    RewriteCond %{HTTP:X-Forwarded-Proto} =https
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
    RewriteRule ^(.+[^/])\$ https://%{HTTP_HOST}\$1/ [redirect,last]

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

    <Directory "${DOCROOTS}">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    <Directory "/var/www/html/.worktrees">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog \${APACHE_LOG_DIR}/access.log combined

    # The TYPO3 backend sets large cookies.
    LimitRequestFieldSize 16380
    Alias "/phpstatus" "/var/www/phpstatus.php"
</VirtualHost>
EOF
    }

    printf '# Generated by the worktree management -- do not edit by hand.\n\n'
    block 80 ''
    block 443 '
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key
'
}

# Which web server actually serves this project -- not "which configuration
# directory is there": DDEV's web image carries nginx and Apache both, so that
# question always answers nginx and an Apache project would be handed a
# configuration nothing reads. DDEV names the one in charge in the environment.
webserver() {
    case "${DDEV_WEBSERVER_TYPE:-}" in
        nginx*) echo nginx ;;
        apache*) echo apache ;;
        *)
            if pgrep -x apache2 >/dev/null 2>&1; then
                echo apache
            elif pgrep -x nginx >/dev/null 2>&1; then
                echo nginx
            fi
            ;;
    esac
}

# Read rather than run: a test sources this for the two functions above and
# applies nothing. Everything below this line touches the container.
[ "${BRANCHERY_SCRIPT_READ_ONLY:-}" = "1" ] && return 0

mkdir -p "$DOCROOTS"

case "$(webserver)" in
    nginx)
        # The other server's copy goes: a project that switched over would
        # otherwise keep being served by a configuration nobody writes any more.
        rm -f /etc/apache2/sites-enabled/zz-branchery.conf
        nginx_config > /etc/nginx/sites-enabled/zz-branchery.conf
        if pgrep -x nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then
            nginx -s reload
        fi
        ;;
    apache)
        rm -f /etc/nginx/sites-enabled/zz-branchery.conf
        apache_config > /etc/apache2/sites-enabled/zz-branchery.conf
        if pgrep -x apache2 >/dev/null 2>&1 && apachectl -t >/dev/null 2>&1; then
            apachectl graceful 2>&1 | grep -vF "Could not reliably determine" || true
        fi
        ;;
esac
